export default {
  PACKAGE_DATA: 'PACKAGE_DATA',
  HISTORY_DATA: 'HISTORY_DATA',
  HISTORY_DATA_REPLACE: 'HISTORY_DATA_REPLACE',
  MODIFY_INPUT: 'MODIFY_INPUT',
  SHOW_DETAILED: 'SHOW_DETAILED',
  SHOW_TOAST_NOTIFY: 'SHOW_TOAST_NOTIFY',
  SET_PHONE: 'SET_PHONE',
  SET_CURRENT_LANGUAGE: 'SET_CURRENT_LANGUAGE',
};
